workflows:
  build-apk:
    name: Build Android APK
    max_build_duration: 30
    environment:
      # android: true    ← احذف هذا السطر
      node: 18.16.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
