workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        ANDROID_SDK_ROOT: "/Users/builder/programs/android-sdk"
    scripts:
      - name: Install Node.js and npm
        script: |
          # تثبيت Node.js 18
          curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
          chmod +x n
          sudo ./n 18.20.2
          
          # إعداد المسارات
          export N_PREFIX="$HOME/n"
          export PATH="$N_PREFIX/bin:$PATH"
          
          # تحديث npm
          npm install -g npm@latest
          
          node -v
          npm -v

      - name: Install project dependencies with npm
        script: |
          # استخدم npm بدلاً من yarn
          npm ci --legacy-peer-deps

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      - name: Build Android debug APK
        script: |
          cd android
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
