workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        ANDROID_SDK_ROOT: "/Users/builder/programs/android-sdk"
    scripts:
      - name: Verify project structure
        script: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          
          # إنشاء مجلد android إذا كان مفقوداً
          if [ ! -d "android" ]; then
            echo "Android folder is missing! Creating a new React Native Android project..."
            
            # إنشاء مشروع مؤقت
            npx react-native init TempProject --version 0.72.6 --template react-native-template-typescript
            
            # نسخ مجلد android من المشروع المؤقت
            cp -R TempProject/android .
            
            # تنظيف الملفات المؤقتة
            rm -rf TempProject
            
            echo "Android project created successfully!"
          else
            echo "Android folder exists. Continuing..."
          fi
          
          # التحقق من محتويات مجلد android
          echo "Android folder contents:"
          ls -la android/

      - name: Install Node.js
        script: |
          # تثبيت Node.js 18
          curl -o node-v18.20.2.pkg https://nodejs.org/dist/v18.20.2/node-v18.20.2.pkg
          sudo installer -pkg node-v18.20.2.pkg -target /
          export PATH="/usr/local/bin:$PATH"
          node -v
          npm -v

      - name: Install project dependencies
        script: |
          # تثبيت الاعتماديات
          npm install --legacy-peer-deps
          
          # إنشاء ملفات Gradle إذا لزم الأمر
          if [ ! -f "android/gradlew" ]; then
            echo "Generating gradlew wrapper..."
            cd android
            ./gradlew wrapper --gradle-version 7.5.1
            cd ..
          fi
          
          # منح صلاحيات التنفيذ
          chmod +x android/gradlew

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          echo "Local properties file content:"
          cat android/local.properties

      - name: Build Android debug APK
        script: |
          cd android
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
