workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        ANDROID_SDK_ROOT: "/Users/builder/programs/android-sdk"
    scripts:
      - name: Install Node.js
        script: |
          # تثبيت Node.js 18 مباشرة بدون n
          curl -o node-v18.20.2.pkg https://nodejs.org/dist/v18.20.2/node-v18.20.2.pkg
          sudo installer -pkg node-v18.20.2.pkg -target /
          export PATH="/usr/local/bin:$PATH"
          node -v
          npm -v

      - name: Install project dependencies
        script: |
          # إنشاء package-lock.json إذا لم يكن موجوداً
          if [ ! -f package-lock.json ]; then
            npm install --legacy-peer-deps --package-lock-only
          fi
          
          # تثبيت الاعتماديات باستخدام npm
          npm ci --legacy-peer-deps

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      - name: Build Android debug APK
        script: |
          cd android
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
