workflows:
  build-apk:
    name: Build Android APK
    max_build_duration: 30
    environment:
      node: 18.16.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build debug APK
        script: |
          cd telon-gateway-app/android
          ./gradlew assembleDebug
    artifacts:
      - telon-gateway-app/android/app/build/outputs/**/*.apk
