workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        ANDROID_SDK_ROOT: "/Users/builder/programs/android-sdk"
    scripts:
      - name: Install Node.js
        script: |
          curl -o node-v18.20.2.pkg https://nodejs.org/dist/v18.20.2/node-v18.20.2.pkg
          sudo installer -pkg node-v18.20.2.pkg -target /
          export PATH="/usr/local/bin:$PATH"
          node -v
          npm -v

      - name: Install project dependencies
        script: |
          if [ ! -f package-lock.json ]; then
            npm install --legacy-peer-deps --package-lock-only
          fi
          npm ci --legacy-peer-deps
          
          # إنشاء gradlew إذا لم يكن موجوداً
          if [ ! -f "android/gradlew" ]; then
            echo "Generating gradlew wrapper..."
            cd android
            ./gradlew wrapper --gradle-version 7.5.1
            cd ..
          fi
          
          # منح صلاحيات التنفيذ
          chmod +x android/gradlew
          
          # التحقق من الملفات
          echo "Android folder contents:"
          ls -la android/

      - name: Set Android SDK location
        script: |
          mkdir -p android
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          echo "File created at: $(pwd)/android/local.properties"

      - name: Build Android debug APK
        script: |
          # الانتقال لمجلد android وتنفيذ البناء
          cd android
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
