workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        ANDROID_SDK_ROOT: "/Users/builder/programs/android-sdk"
    scripts:
      - name: Install Node.js using n
        script: |
          # تثبيت أداة n لإدارة إصدارات Node.js
          curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
          chmod +x n
          sudo ./n 18.20.2  # تثبيت إصدار محدد بدقة
          
          # إعداد المسارات
          export N_PREFIX="$HOME/n"
          export PATH="$N_PREFIX/bin:$PATH"
          
          # تثبيت yarn
          npm install -g yarn@1.22.19
          node -v
          yarn -v

      - name: Install project dependencies
        script: |
          yarn install --frozen-lockfile

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      - name: Build Android debug APK
        script: |
          cd android
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
