workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        ANDROID_SDK_ROOT: "/Users/builder/programs/android-sdk"
    scripts:
      - name: Create Android project structure
        script: |
          echo "Creating Android project structure..."
          if [ ! -d "android" ]; then
            mkdir -p android/app/src/main/java/com/yourproject
            mkdir -p android/app/src/main/res
            mkdir -p android/gradle/wrapper

            touch android/settings.gradle
            touch android/build.gradle
            touch android/gradlew
            touch android/gradle/wrapper/gradle-wrapper.properties
            touch android/app/build.gradle
            touch android/app/src/main/AndroidManifest.xml
            touch android/app/src/main/java/com/yourproject/MainActivity.java

            echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-bin.zip" > android/gradle/wrapper/gradle-wrapper.properties
            echo "buildscript {
                repositories {
                    google()
                    mavenCentral()
                }
                dependencies {
                    classpath(\"com.android.tools.build:gradle:7.3.1\")
                }
            }" > android/build.gradle
            echo "rootProject.name = 'YourProject'" > android/settings.gradle
            echo "apply plugin: \"com.android.application\"
            android {
                compileSdkVersion 33
                defaultConfig {
                    applicationId \"com.yourproject\"
                    minSdkVersion 21
                    targetSdkVersion 33
                    versionCode 1
                    versionName \"1.0\"
                }
            }
            dependencies {
                implementation 'com.facebook.react:react-native:+'
            }" > android/app/build.gradle
            echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
            <manifest xmlns:android=\"http://schemas.android.com/apk/res/android\">
                <application>
                    <activity android:name=\".MainActivity\" />
                </application>
            </manifest>" > android/app/src/main/AndroidManifest.xml
            echo "package com.yourproject;
            import com.facebook.react.ReactActivity;
            public class MainActivity extends ReactActivity {
                @Override
                protected String getMainComponentName() {
                    return \"YourProject\";
                }
            }" > android/app/src/main/java/com/yourproject/MainActivity.java

            chmod +x android/gradlew
            echo "Android structure created!"
          fi
          echo "Gradlew exists: $(ls android/gradlew 2>/dev/null && echo 'Yes' || echo 'No')"

      - name: Install Node.js
        script: |
          curl -o node-v18.20.2.pkg https://nodejs.org/dist/v18.20.2/node-v18.20.2.pkg
          sudo installer -pkg node-v18.20.2.pkg -target /
          export PATH="/usr/local/bin:$PATH"
          node -v

      - name: Install project dependencies
        script: |
          echo '{
            "name": "telon-gsm-sip-gateway",
            "version": "1.0.0",
            "dependencies": {
              "react": "18.2.0",
              "react-native": "0.72.6",
              "@react-native-community/cli": "^11.0.0"
            }
          }' > package.json
          npm install --legacy-peer-deps
          npm ls react react-native @react-native-community/cli

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      - name: Build Android debug APK
        script: |
          echo "Starting APK build..."
          cd android
          ./gradlew assembleDebug --stacktrace
          echo "Checking APK output..."
          ls -la app/build/outputs/apk/debug/
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
